// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Domain.Entity;
using Domain.Entity.Identity;
using IdentityApi.Domain.EntityMap;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System.Security;
using Xg.Cloud.Core;

namespace Domain.EntityMap.Identity
{
    public class MenuMap : BaseEntityConfiguration<Menu>
    {
        public override void ConfigureCustomFields(EntityTypeBuilder<Menu> builder)
        {
            // ===================== 表配置 =====================
            builder.ToTable("sys_menu");

            // ===================== 字段配置 =====================
            // 父级菜单ID
            builder.Property(t => t.Pid)
                   .HasColumnName("p_id")
                   .HasComment("父级菜单ID");

            // 菜单类型 (目录/菜单/按钮)
            builder.Property(t => t.Category)
                   .HasColumnName("category")
                   .IsRequired()
                   .HasComment("菜单类型: 1-目录, 2-菜单, 3-按钮");

            // 菜单元数据标题
            builder.Property(t => t.MetaTitle)
                   .HasColumnName("meta_title")
                   .HasMaxLength(100)
                   .HasComment("菜单显示标题");

            // 菜单图标
            builder.Property(t => t.MetaIcon)
                   .HasColumnName("meta_icon")
                   .HasMaxLength(100)
                   .HasComment("菜单图标类名或URL");

            // 路由名称 (Vue Router name)
            builder.Property(t => t.Name)
                   .HasColumnName("name")
                   .HasMaxLength(100)
                   .HasComment("路由唯一标识名称");

            // 前端组件路径
            builder.Property(t => t.Component)
                   .HasColumnName("component")
                   .HasMaxLength(200)
                   .HasComment("前端组件路径 (如: /system/user/index)");

            // 重定向路径
            builder.Property(t => t.Redirect)
                   .HasColumnName("redirect")
                   .HasMaxLength(200)
                   .HasComment("路由重定向路径");

            // 路由访问路径
            builder.Property(t => t.Path)
                   .HasColumnName("path")
                   .HasMaxLength(200)
                   .HasComment("路由访问路径 (如: /system/user)");

            // 权限标识
            builder.Property(t => t.Permission)
                   .HasColumnName("permission")
                   .HasMaxLength(100)
                   .HasComment("接口权限标识 (如: system:user:list)");

            // 排序序号
            builder.Property(t => t.SortNo)
                   .HasColumnName("sort_no")
                   .HasDefaultValue(0)
                   .HasComment("同级菜单排序序号");
        }
    }
}
