// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Domain.Entity;
using Domain.Entity.Identity;
using IdentityApi.Domain.EntityMap;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Xg.Cloud.Core;

namespace Domain.EntityMap.Identity
{
    public class RoleMenuMap : BaseEntityConfiguration<RoleMenu>
    {
        public override void ConfigureCustomFields(EntityTypeBuilder<RoleMenu> builder)
        {
            // ===================== 表配置 =====================
            builder.ToTable("sys_role_menu");  // 统一 snake_case

            // ===================== 字段配置 =====================
            // 菜单ID（外键字段）
            builder.Property(t => t.MenuId)
                   .HasColumnName("menu_id")
                   .IsRequired()
                   .HasComment("关联菜单ID");

            // 角色ID（外键字段）
            builder.Property(t => t.RoleId)
                   .HasColumnName("role_id")
                   .IsRequired()
                   .HasComment("关联角色ID");
        }
    }
}
