// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Domain.Entity.Identity;
using IdentityApi.Domain.EntityMap;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Domain.EntityMap.Identity
{
    public class RoleMap : BaseEntityConfiguration<Role>
    {
        public override void ConfigureCustomFields(EntityTypeBuilder<Role> builder)
        {
            // ===================== 表配置 =====================
            builder.ToTable("sys_role");

            // ===================== 字段配置 =====================
            // 角色名称
            builder.Property(t => t.Name)
                   .HasColumnName("name")
                   .HasMaxLength(50)
                   .IsRequired()
                   .HasComment("角色名称（如：系统管理员）");

            // 角色描述
            builder.Property(t => t.Description)
                   .HasColumnName("description")
                   .HasMaxLength(200)
                   .HasComment("角色职责描述");

            // 角色等级（数值越小权限越高）
            builder.Property(t => t.Level)
                   .HasColumnName("level")
                   .IsRequired()
                   .HasComment("角色等级：1-超级管理员, 2-普通管理员, 3-操作员");

            // 排序序号
            builder.Property(t => t.SortNo)
                   .HasColumnName("sort_no")
                   .HasDefaultValue(0)
                   .HasComment("同级角色排序序号");
        }
    }
}
