// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Domain.Entity;
using Domain.Entity.Identity;
using IdentityApi.Domain.EntityMap;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Xg.Cloud.Core;

namespace Domain.EntityMap.Identity
{
    public class UserRoleMap : BaseEntityConfiguration<UserRole>
    {
        public override void ConfigureCustomFields(EntityTypeBuilder<UserRole> builder)
        {
            // ===================== 表配置 =====================
            builder.ToTable("sys_user_role"); // 统一 snake_case

            // ===================== 字段配置 =====================
            // 用户ID（外键）
            builder.Property(t => t.UserId)
                   .HasColumnName("user_id")
                   .IsRequired()
                   .HasComment("关联用户ID");

            // 角色ID（外键）
            builder.Property(t => t.RoleId)
                   .HasColumnName("role_id")
                   .IsRequired()
                   .HasComment("关联角色ID");
        }
    }
}
