//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Cloud.Domain.Entities;
using System.ComponentModel.DataAnnotations;


namespace Domain.Entity.Dictionary
{
    /// <summary>
	/// 数据字典明细表
	/// </summary>
    public class GlobalDataDetail :BaseEntity<long>
    {
        /// <summary>
	    /// 字段编码
        ///</summary>
        public string Code { get; set; }
        /// <summary>
	    /// 名称
        ///</summary>
        public string Name { get; set; }
        /// <summary>
	    /// 备注
        ///</summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 字典关键值
        ///</summary>
        public string ConstKey { get; set; }
        /// <summary>
	    /// 排序码-正序
	    /// </summary>
        public int SortNo { get; set; }

    }
}