apiVersion: v1
kind: Namespace
metadata:
  name: <env>-backend-<project>
---
apiVersion: apps/v1	#与k8s集群版本有关，使用 kubectl api-versions 即可查看当前集群支持的版本
kind: Deployment	#该配置的类型，我们使用的是 Deployment
metadata:	        #译名为元数据，即 Deployment 的一些基本属性和信息
  name: <env>-backend-<project>-deployment	#Deployment 的名称
  namespace: <env>-backend-<project>
  labels:	    #标签，可以灵活定位一个或多个资源，其中key和value均可自定义，可以定义多组，目前不需要理解
    app: <env>-backend-<project>	#为该Deployment设置key为app，value为nginx的标签
    service: <env>-backend-<project>-identity
spec:	        #这是关于该Deployment的描述，可以理解为你期待该Deployment在k8s中如何使用
  replicas: 1	#使用该Deployment创建一个应用程序实例
  revisionHistoryLimit: 1
  selector:	    #标签选择器，与上面的标签共同作用，目前不需要理解
    matchLabels: #选择包含标签app:<env>-backend-<project>的资源
      #app: <env>-backend-<project>
      service: <env>-backend-<project>-identity
  template:	    #这是选择或创建的Pod的模板
    metadata:	#Pod的元数据
      labels:	#Pod的标签，上面的selector即选择包含标签app:nginx的Pod
        app: <env>-backend-<project>
        service: <env>-backend-<project>-identity
      #annotations:
      #  dapr.io/enabled: "true"
      #  dapr.io/app-id: "identity-api"
      #  dapr.io/app-port: "80"
      #  dapr.io/log-level: "error"
      #  dapr.io/sidecar-listen-addresses: "0.0.0.0"
    spec:	    #期望Pod实现的功能（在pod中部署）
      tolerations:
       - key: node-role.kubernetes.io/master
         operator: Exists
         effect: NoSchedule
      containers:	#生成container，与docker中的container是同一种
      - name: <env>-backend-<project>-identity	#container的名称
        image: xxxx-xxxx:xx	
        imagePullPolicy: IfNotPresent
        resources:              ##CPU内存限制
            requests:
                memory: 100Mi
            limits:
                memory: 1000Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <env>-backend-<project>-ingress
  namespace: <env>-backend-<project>
  annotations:
    # kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/configuration-snippets: |
      rewrite ^/<env>-backend-<project>/(.*)$ /$1/ redirect;
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix:  "<env>-backend-<project>"
spec:
  ingressClassName: "nginx"
  rules:
  - host: <HOST_NAME>
    http:
      paths:
       - pathType: Prefix
         path: /<env>-backend-<project>(/|$)(.*)
         backend:
           service:
             name: <env>-backend-<project>-service
             port:
               number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: <env>-backend-<project>-service	 #Service 的名称
  namespace: <env>-backend-<project>
  labels:     	#Service 自己的标签
    app: <env>-backend-<project>	#为该 Service 设置 key 为 app，value 为 <env>-backend-<project> 的标签
    service: <env>-backend-<project>-identity
spec:	    #这是关于该 Service 的定义，描述了 Service 如何选择 Pod，如何被访问
  selector:	    #标签选择器
    #app: <env>-backend-<project> #选择包含标签 app:<env>-backend-<project> 的 Pod
    service: <env>-backend-<project>-identity
  ports:
  - name: <env>-backend-<project>-port	#端口的名字
    protocol: TCP	    #协议类型 TCP/UDP
    port: 80	        #集群内的其他容器组可通过 80 端口访问 Service
    #nodePort: 32700   #通过任意节点的 32600 端口访问 Service
    targetPort: 80	#将请求转发到匹配 Pod 的 80 端口
  #- port: 81
  #  targetPort: 3500
  #  protocol: TCP
  #  name: daprhttp
  #- port: 50001
  #  targetPort: 50001
  #  protocol: TCP
  #  name: daprgrpc
  type: ClusterIP	#Serive的类型，ClusterIP/NodePort/LoaderBalancer