@echo off
setlocal enabledelayedexpansion

:: 使用WMIC获取标准化时间（兼容所有语言环境）
for /f "tokens=1-6 delims=.-/ " %%a in ('wmic os get localdatetime ^| find "."') do (
    set "datetime=%%a"
)

:: 从标准化时间字符串中截取各字段（格式：YYYYMMDDHHMMSS）
set "year=!datetime:~0,4!"
set "month=!datetime:~4,2!"
set "day=!datetime:~6,2!"
set "hour=!datetime:~8,2!"
set "minute=!datetime:~10,2!"
set "second=!datetime:~12,2!"

:: 生成时间戳（格式：YYYYMMDD_HHMMSS）
set "timestamp=!year!!month!!day!_!hour!!minute!!second!"

@echo "update migrations start"
dotnet ef migrations add AutoGenerated_%timestamp%
@echo "update migrations end"

@echo "update database start"
dotnet ef database update
@echo "update database end"

pause