//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Cloud.Domain.Entities;
namespace Identity.Shared.Dto.Admin.General
{
    /// <summary>
	///数据字典明细表dto
	/// </summary>
    public class GlobalDataDetailDto : BaseEntity<long>
    {
        /// <summary>
        /// 
        /// </summary>
        public string Code { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string Remark { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public string ConstKey { get; set; }
        /// <summary>
	    /// 
	    /// </summary>
        public int SortNo { get; set; }
    }
}