//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Cloud.Domain.Entities;
using System;
using System.Collections.Generic;

namespace Identity.Shared.Dto
{
    /// <summary>
	/// sys_role
	/// </summary>
    public class RoleDto: BaseEntity<long>
    {
        /// <summary>
	    /// 角色名称
	    /// </summary>
        public string Name { get; set; }
        /// <summary>
	    /// 角色描述
	    /// </summary>
        public string Description { get; set; }
        /// <summary>
	    /// 创建时间
	    /// </summary>
        public DateTime CreateTime { get; set; } = DateTime.Now;
        /// <summary>
	    /// 更新时间
	    /// </summary>
        public DateTime UpdateTime { get; set; } = DateTime.Now;
        /// <summary>
	    /// 创建人
	    /// </summary>
        public long CreateUserId { get; set; }
        /// <summary>
	    /// 更新人
	    /// </summary>
        public long UpdateUserId { get; set; }
        /// <summary>
        /// 级别 （0级最大）
        /// </summary>
        public int Level { get; set; }
        /// <summary>
        /// 菜单id集合
        /// </summary>
        public virtual List<long> RoleMenuIds { get; set; }
    }
}