//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Cloud.Domain.Entities;
using Identity.Shared;
using System.ComponentModel.DataAnnotations;

namespace Domain.Entity.Identity
{
    /// <summary>
	/// sys_menu
	/// </summary>
    public class Menu:BaseEntity<long>
    {

        /// <summary>
	    /// 名称
        ///</summary>
        public string Name { get; set; }
        /// <summary>
        /// 菜单类型（1：菜单 2：按钮）
        /// </summary>
        public int Category { get; set; }
        /// <summary>
        /// 菜单标题
        ///</summary>
        public string MetaTitle { get; set; }
        /// <summary>
        /// 菜单图标
        ///</summary>
        public string MetaIcon { get; set; }

        /// <summary>
        /// 父类Id
        /// </summary>
        public long Pid { get; set; }
        /// <summary>
        /// 菜单路径-命名下即可，类似menu
        ///</summary>
        public string Path { get; set; }
        /// <summary>
        /// 路由地址-空的用LAYOUT，非空的用类似/system/menu/index
        ///</summary>
        public string Component { get; set; }
        /// <summary>
        /// 权限标识
        ///</summary>
        public string Permission { get; set; }
        /// <summary>
	    /// 跳转地址（一般首页用）
        ///</summary>
        public string Redirect { get; set; }

        /// <summary>
	    /// 排序码
	    /// </summary>
        public int SortNo { get; set; }

    }
}