//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using Cloud.Domain.Entities;

namespace Domain.Entity.Identity
{
    /// <summary>
	/// 权限表
	/// </summary>
    public class RoleMenu : BaseEntity<long>
    {
        public RoleMenu()
        {
        }

        /// <summary>
	    /// 菜单Id
	    /// </summary>
        public long MenuId { get; set; }

        /// <summary>
	    /// 角色ID
	    /// </summary>
        public long RoleId { get; set; }

    }
}