import { status } from 'nprogress';
import { PrimaryTableCol, TableRowData } from 'tdesign-vue-next';

const COLUMNS: PrimaryTableCol<TableRowData>[] = [
  {
    title: '商户号',
    fixed: 'left',
    width: 220,
    ellipsis: true,
    align: 'left',
    colKey: 'mid',
  },
  {
    title: '支付银行支付银行信息',
    width: 220,
    ellipsis: true,
    align: 'left',
    colKey: 'bankCardNo',
  },
  {
    title: '银行信息',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey: 'bankInfo',
  },      
  {
    title: '资金渠道',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'billFunds',
  }, 
  {
    title: '资金渠道说明',
    width: 200,
    ellipsis: true,
    align: 'left',
    colKey:'billFundsDesc',
  }, 
  {
    title: '卖家ID',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'buyerId',
  }, 
  {
    title: '买家用户名',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'buyerUsername',
  }, 
  {
    title: '实付金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'buyerPayAmount',
  }, 
  {
    title: '实付现金金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'buyerCashPayAmt',
  }, 
  {
    title: '优惠金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'couponAmount',
  }, 
  {
    title: '订单金额（单位：分）',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'totalAmount',
  }, 
  {
    title: '开票金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'invoiceAmount',
  }, 
  {
    title: '商户订单号',
    width: 220,
    ellipsis: true,
    align: 'left',
    colKey:'merOrderId',
  },  
  {
    title: '支付时间',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'payTime',
  }, 
  {
    title: '实收金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'receiptAmount',
  }, 
  {
    title: '支付银行卡参考号',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refId',
  }, 
  {
    title: '退款金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refundAmount',
  }, 
  {
    title: '退款说明',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refundDesc',
  }, 
  {
    title: '系统交易流水号',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'seqId',
  }, 
  {
    title: '结算日期',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'settleDate',
  }, 
  {
    title: '订单状态',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'status',
  }, 
  {
    title: '卖家子ID' ,
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'subBuyerId',
  },   
  {
    title: '渠道订单号 ',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'targetOrderId',
  },  
  {
    title: '支付渠道',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'targetSys',
  },  
  {
    title: '商户出资优惠金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'couponMerchantContribute',
  }, 
  {
    title: '其他出资优惠金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'couponOtherContribute',
  }, 
  {
    title: '微信活动Id',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'activityIds',
  }, 
  {
    title: '退货渠道订单号',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refundTargetOrderId',
  }, 
  {
    title: '退货时间',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refundPayTime',
  }, 
  {
    title: '结算日期',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refundSettleDate',
  }, 
  {
    title: '订单详情',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'orderDesc',
  }, 
  {
    title: '订单创建时间',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'createTime',
  }, 
  {
    title: '商户UUID',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'mchntUuid',
  }, 
  {
    title: '转接系统',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'connectSys',
  }, 
  {
    title: '商户所属分支机构代码',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'subInst',
  }, 
  {
    title: '退货外部订单号',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refundExtOrderId',
  }, 
  {
    title: '商品交易单号',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'goodsTradeNo',
  }, 
  {
    title: '外部订单号',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'extOrderId',
  }, 
  {
    title: '退货订单号',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refundOrderId',
  }, 
  {
    title: '实退现金金额',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'refundInvoiceAmount',
  }, 
  {
    title: '分期付款信息域',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'instalTransInfo',
  }, 
  {
    title: '实际通知回调时间',
    width: 160,
    ellipsis: true,
    align: 'left',
    colKey:'notifyDate',
  },   
];
const PAGINATION = {
  current: 1,
  pageSize: 10,
  total: 0,
};
const SEARCHFORM = {
  orderNo: '',
  userId: null,
  createTime: [],
  status: null,
  detailStatus: null,
};
export { COLUMNS, PAGINATION, SEARCHFORM };
